- name: Generate provider yaml
  template:
    src: provider.j2.yml
    dest: /tmp/provider.yml

- name: Display generated yaml
  command: cat /tmp/provider.yml
  register: output

- name: Create resource
  kubernetes.core.k8s:
    state: present
    src: /tmp/provider.yml

- debug:
    var: output.stdout_lines
